---
AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon EKS Using CloudFormation Template

Parameters:

  RoleName:
    Type: String
    Description: AmazonEKSServicePolicy policy for the AWSServiceRoleForAmazonEKS IAM role

Resources:
  ClusterRole:
    Description: Allows EKS to manage clusters on your behalf.
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
            Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
